version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mypassword
      MONGO_INITDB_DATABASE: mongodb
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: File_Stream_Bot
    command: python3 -m biisal
    depends_on:
      - mongodb
    environment:
      bot_name: StreamBot
      bisal__channel: https://telegram.me/+HnHRP92TZClhZWFl
      bisal_grp: https://telegram.me/+UUJXMvEtEpg2MTA9
      API_ID: 2753868
      API_HASH: ab6ec1d5a69f52224f558f6295576614
      BOT_TOKEN: 6075501282:AAEvhoTJbddTd1sBRNxanJhU9kLVUi7aADU
      name: IvastreamBot  # Changed NAME to name for consistency
      BIN_CHANNEL: -1002472125476
      NEW_USER_LOG: -1002449815454
      PORT: 8080
      WEB_SERVER_BIND_ADDRESS: 144.24.121.110
      OWNER_ID: 5809046691
      OWNER_USERNAME: iva4ubot
      FQDN: 144.24.121.110:8080
      DATABASE_URL: "mongodb://admin:mypassword@mongodb:27017/mongodb?authSource=admin"
      UPDATES_CHANNEL: iva_files
    volumes:
      - .:/app

volumes:
  mongodb_data: